export const WALLET_MEMBER_ROLES = Object.freeze({
  OWNER: 'OWNER',
  COLLABORATOR: 'COLLABORATOR',
  VIEWER: 'VIEWER',
})

export const WALLET_MEMBER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REMOVED: 'REMOVED',
})
